services:
  angular:
    container_name: angular_container
    image: swcomp/angular_nginx
    build: ./angular_dev
    hostname: angular
    ports:
      - 80:80
    volumes:
      - ./angular_dev/hello-world-angular:/usr/share/nginx/html:Z
    networks:
      - sw_network
    depends_on:
      - "scala"

  scala:
    container_name: scala_container
    image: swcomp/scala
    build: ./scala
    hostname: scala
    volumes:
      - .scala/src/:/HelloWorld/src
    ports:
      - 8081:8081
    environment:
      - PSQLHOST=postgres:5432
      - PSQLUSER=scalauser
      - PSQLPASSWD=example
    networks:
      - sw_network
    depends_on:
      - "postgres"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/" ]
      interval: 30s
      timeout: 10s
      retries: 10

  postgres:
    container_name: postgres_container
    image: swcomp/postgres
    build: ./postgres
    hostname: postgres
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: scalauser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: defaultdb
    networks:
      - sw_network
  
networks:
  sw_network:
    driver: bridge
    name: sw_network

