services:
  angular:
    image: swcomp/angular_nginx
    build: ./angular_dev
    hostname: angular
    ports:
      - 80:80
    volumes:
      - ./angular_dev/hello-world-angular:/usr/share/nginx/html:Z
    networks:
      - sw_network
    depends_on:
      - "scala"

  scala:
    image: swcomp/scala
    build: ./scala
    hostname: scala
    volumes:
      - ./scala:/HelloWorld
    ports:
      - 8081:8081
    environment:
      - PSQLHOST=postgres:5432
      - PSQLUSER=scalauser
      - PSQLPASSWD=example
    networks:
      - sw_network
    depends_on:
      - "postgres"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/" ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: swcomp/postgres
    build: ./postgres
    hostname: postgres
    environment:
      POSTGRES_USER: scalauser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: defaultdb
    networks:
      - sw_network

networks:
  sw_network:
    driver: bridge
    name: sw_network
