services:
  angular:
    image: angular_main
    hostname: angular
    ports:
      - 80:80
    volumes:
      - ./angular_dev/hello-world-angular:/usr/share/nginx/html
    networks:
      - sw_network

  scala:
    image: scala_main
    hostname: scala
    ports:
      - 8081:8081
    environment:
      - PSQLHOST=postgres:5432
    networks:
      - sw_network

  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: scalauser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: defaultdb
    networks:
      - sw_network
    environment: 
      POSTGRES_PASSWORD: test
  
networks:
  sw_network:
    driver: bridge
    name: sw_network
<<<<<<< HEAD
<<<<<<< HEAD
=======

>>>>>>> testing
=======

>>>>>>> 01fc1bf9b4802639fe0e386aadad0907214bb1e9
