openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'SW component manager API'
  description: 'The API for Software release component management software.'
  contact:
    name: Kaisa
    email: kaisa.sormunen@tuni.fi

paths:
  /releases:
    post:
      description: Get infromation of all releases in the db.
      responses:
        200:
          description: Successful pull of release data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        401:
          description: User has not been authenticated.
        403:
          description: User is not authorized to view the results.
        404:
          description: No releases were found in the database.

  /releases/{releaseName}:
    post:
      description: Get information of releases from db.
      parameters:
        - name: releaseName
          in: path
          required: true
          description: Define one release to get.
          schema:
            type: string
      responses:
        200:
          description: Successfull pull of release data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        400:
          description: The given resourceName is invalid.
        401:
          description: User has not been authenticated.
        403:
            description: User is not authorized to view the results.
        404:
          description: A release with the specified releasenName was not found.
    put:
      description: Create a new release to database.
      parameters:
        - name: releaseName
          in: path
          required: true
          description: Name to use while creating a new release to database.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        201:
          description: Resource created.
        400:
          description: The given releaseName is invalid.
        401:
          description: User has not been authenticated.
        403:
          description: User is not authorized to create new releases.
        409:
          description: The given releaseName is already in use.

  /compareReleases/{releaseName1}:{releaseName2}: #TODO FIX WHEN UP TO DATE
    post:
      description: Compare two different releases and their packages.

      parameters:
        - name: releaseName1
          in: path
          required: true
          description: Name to use retrieving and comparing release packages.
          schema:
            type: string

        - name: releaseName2
          in: path
          required: true
          description: Name to use retrieving and comparing release packages.
          schema:
            type: string

      responses:
        200:
          description: Successfull retrieval and comparison of data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        400:
          description: One or both of the given releaseName are invalid.
        401:
          description: User has not been authenticated.
        403:
          description: User is not authorized to create new releases.

  /insertModule:
    put:
      description: Insert module to db

      parameters:
        - name: jsonBody
            in: body
            required: true
            description: Json with module parameters
            schema:
              type: json

      example:
        body:
          {
            "name": "TestInsertModule"
          }

      responses:
        200:
          description:
          content:
            application/json:
              schema:
                type: json
                items:
                  type: string
        400:
          description: Request body was invalid

  /insertComponent:
    put:
      description: Insert component to db

      parameters:
        - name: jsonBody
            in: body
            required: true
            description: Json with component parameters
            schema:
              type: json

      example:
        body:
          { "name": "componentname",
            "url": "urlforcomp.com",
            "version": "1.2",
            "license": "exlicence",
            "copyright": "coppyright"
          }

      responses:
        200:
          description:
          content:
            application/json:
              schema:
                type: json
                items:
                  type: string
        400:
          description: Request body was invalid

  /insertSubComponent:
    put:
      description: Insert subcomponent to db

      parameters:
        - name: jsonBody
            in: body
            required: true
            description: Json with subComponent parameters
            schema:
              type: json

      example:
        body:
          {
            "name": "subcomponentname",
            "url": "urlforsubcomp.com",
            "version": "1.2",
            "license": "exlicence",
            "copyright": "coppyright"
          }

      responses:
        200:
          description:
          content:
            application/json:
              schema:
                type: json
                items:
                  type: string
        400:
          description: Request body was invalid

  /insertComponentToModule:
    put:
      description: Insert component to module relation to db

      parameters:
        - name: jsonBody
            in: body
            required: true
            description: Json with subComponent to module relation parameters
            schema:
              type: json

      example:
        body:
          {
            "modulename": "TestInsertModule",
            "componentname": "test",
            "usage_type": "String",
            "attr_value1": "String",
            "attr_value2": "String",
            "attr_value3": "String",
            "date": "1.2.2021",
            "comment_one": "String",
            "comment_two": "String"
          }

      responses:
        200:
          description:
          content:
            application/json:
              schema:
                type: json
                items:
                  type: string
        400:
          description: Request body was invalid

  /insertSubToComponent:
    put:
      description: Insert subcomponent to component relation

      parameters:
        - name: jsonBody
            in: body
            required: true
            description: Json with subComponent to module relation parameters
            schema:
              type: json

      example:
        body:
          {
            "componentname": "nameofcomponent",
            "subcomponentname": "nameofsubcomponent"
          }

      responses:
        200:
          description:
          content:
            application/json:
              schema:
                type: json
                items:
                  type: string
        400:
          description: Request body was invalid

  /components:
      post:
        description: Get info on all components in the db.
        responses:
          200:
            description: Successful pull of component data.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: string
          401:
            description: User has not been authenticated.
          403:
            description: User is not authorized to view the results.
          404:
            description: No components were found in the database.
